rss-url: https://news.google.com/rss/search?q=AI&hl=ja&gl=JP&ceid=JP:ja
max-articles: 5
model: gpt-4o
system-prompt: |
  あなたは日本語で要約を行うアシスタントです。
user-prompt: |
  以下はAI関連のニュースです。簡潔にわかりやすく日本語で要約してください。

  タイトル: {title}
  内容: {content}
